#!/usr/bin/env python3
"""
PR Code Review Script - Azure OpenAI Integration

Analyzes pull request changes and posts code review comments using Azure OpenAI GPT-5.
"""

import os
import subprocess
import sys
import json
from typing import Optional

try:
    from openai import AzureOpenAI
    import requests
except ImportError:
    print("ERROR: Required packages not installed. Run: pip install openai requests")
    sys.exit(1)


def get_pr_diff(pr_number: int, target_branch: str) -> Optional[str]:
    """Fetch the diff for a PR from GitHub."""
    try:
        github_pat = os.getenv('GITHUB_PAT')
        repo_owner = os.getenv('REPO_OWNER', 'vaibhavsaxena619')
        repo_name = os.getenv('REPO_NAME', 'poc-auto-pr-fix')
        
        if not github_pat:
            print("ERROR: GITHUB_PAT not set")
            return None
        
        headers = {
            'Authorization': f'token {github_pat}',
            'Accept': 'application/vnd.github.v3.diff'
        }
        
        url = f"https://api.github.com/repos/{repo_owner}/{repo_name}/pulls/{pr_number}"
        response = requests.get(url, headers=headers)
        
        if response.status_code != 200:
            print(f"ERROR: Failed to fetch PR #{pr_number}: {response.status_code}")
            return None
        
        return response.text
    except Exception as e:
        print(f"ERROR: Failed to get PR diff: {e}")
        return None


def analyze_code_with_gpt(diff: str) -> Optional[str]:
    """Send code diff to Azure OpenAI for analysis."""
    try:
        api_key = os.getenv('AZURE_OPENAI_API_KEY')
        endpoint = os.getenv('AZURE_OPENAI_ENDPOINT')
        api_version = os.getenv('AZURE_OPENAI_API_VERSION', '2024-12-01-preview')
        deployment_name = os.getenv('AZURE_OPENAI_DEPLOYMENT_NAME', 'gpt-5')
        
        if not api_key or not endpoint:
            print("ERROR: Azure OpenAI credentials not set")
            return None
        
        client = AzureOpenAI(
            api_key=api_key,
            api_version=api_version,
            azure_endpoint=endpoint
        )
        
        prompt = f"""Perform a code review on the following Git diff. Provide constructive feedback on:
1. Possible bugs or issues
2. Code quality improvements
3. Performance considerations
4. Security concerns
5. Best practices violations

Format your response as a GitHub review comment with clear sections.

DIFF:
{diff}

Provide concise, actionable feedback."""
        
        response = client.chat.completions.create(
            model=deployment_name,
            messages=[
                {
                    "role": "system",
                    "content": "You are an expert code reviewer. Provide constructive feedback on code changes."
                },
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            temperature=0.7,
            max_tokens=1500
        )
        
        return response.choices[0].message.content
    except Exception as e:
        print(f"ERROR: Failed to analyze code with GPT: {e}")
        return None


def post_review_comment(pr_number: int, review_body: str) -> bool:
    """Post a review comment to the PR."""
    try:
        github_pat = os.getenv('GITHUB_PAT')
        repo_owner = os.getenv('REPO_OWNER', 'vaibhavsaxena619')
        repo_name = os.getenv('REPO_NAME', 'poc-auto-pr-fix')
        
        if not github_pat:
            print("ERROR: GITHUB_PAT not set")
            return False
        
        headers = {
            'Authorization': f'token {github_pat}',
            'Accept': 'application/vnd.github.v3+json'
        }
        
        # Format review as PR comment
        formatted_comment = f"""## 🤖 Automated Code Review

{review_body}

---
*This review was generated by Azure OpenAI GPT-5 on {pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S')}*
"""
        
        url = f"https://api.github.com/repos/{repo_owner}/{repo_name}/issues/{pr_number}/comments"
        payload = {"body": formatted_comment}
        
        response = requests.post(url, headers=headers, json=payload)
        
        if response.status_code in [200, 201]:
            print(f"✓ Review comment posted to PR #{pr_number}")
            return True
        else:
            print(f"ERROR: Failed to post comment: {response.status_code}")
            print(f"Response: {response.text}")
            return False
    except Exception as e:
        print(f"ERROR: Failed to post review comment: {e}")
        return False


def main():
    """Main PR review workflow."""
    if len(sys.argv) < 3:
        print("Usage: python pr_review.py <pr_number> <target_branch> [source_branch]")
        sys.exit(1)
    
    pr_number = sys.argv[1]
    target_branch = sys.argv[2]
    source_branch = sys.argv[3] if len(sys.argv) > 3 else "Dev_Low"
    
    print(f"[PR Review] Processing PR #{pr_number} to {target_branch} from {source_branch}")
    
    # Get PR diff
    print("Fetching PR changes...")
    diff = get_pr_diff(int(pr_number), target_branch)
    
    if not diff:
        print("✗ Failed to fetch PR diff")
        sys.exit(1)
    
    print(f"✓ Retrieved diff ({len(diff)} bytes)")
    
    # Skip review if read-only mode
    if os.getenv('READ_ONLY_MODE', 'false').lower() == 'true':
        print("ℹ️ READ_ONLY_MODE: Skipping API calls")
        sys.exit(0)
    
    # Analyze with GPT
    print("Analyzing code with Azure OpenAI GPT-5...")
    review = analyze_code_with_gpt(diff)
    
    if not review:
        print("✗ Failed to analyze code")
        sys.exit(1)
    
    print("✓ Code analysis complete")
    print("\n--- Review Output ---")
    print(review)
    print("--- End Review ---\n")
    
    # Post review
    print("Posting review comment to GitHub...")
    if post_review_comment(int(pr_number), review):
        print(f"✓ PR #{pr_number} review completed successfully")
        sys.exit(0)
    else:
        print(f"✗ Failed to post review for PR #{pr_number}")
        sys.exit(1)


if __name__ == "__main__":
    main()
